### ISSUE TITLE
How to apply UTF16 decoder to backscanner?

### ISSUE THREAD

**Issue by yusufozturk** [icza/backscanner#3]
Hi,

We would like to read UTF16 file but when we transform into the string, it adds characters between words.

Is there a way to add decoder to backscanner? Like this one:

https://play.golang.org/p/-9t0D_DFTA

Thanks.

**Comment by icza** [comment]
For this lib to be able to scan backwards, it requires an `io.ReaderAt` (instead of the more common `io.Reader`).

Unfortunately the `golang.org/x/text/transform` package only provides `io.Reader` implementation, not `io.ReaderAt`. So you can't use this lib with `golang.org/x/text/transform`. If you find another package that does provide `io.ReaderAt` (or you implement it yourself), then you'll be able to use `backscanner` with that.

**Comment by yusufozturk** [comment]
Thanks, due to this requirement I had to move to bufio back :( I will be looking to do this.
